config/routes.rb
Rails.application.routes.draw do
  root 'codes#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  resource :voice, only: [], controller: 'voice' do
    member do
      get 'start'
      get 'check'
      get 'real_human'
    end
  end

  resources :codes

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/code.rb
class Code < ActiveRecord::Base
  validates :code, numericality: { only_integer: true }, length: { is: 4 }, presence: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :set_code, only: [:show, :edit, :update, :destroy]

  def index
    @codes = Code.all
  end

  def new
    @code = Code.new
  end

  def edit
  end

  def create
    @code = Code.new(code_params)

    if @code.save
      redirect_to codes_path, notice: 'Code was successfully created.'
    else
      render :new
    end
  end

  def update
    if @code.update(code_params)
      redirect_to codes_path, notice: 'Code was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @code.destroy
    redirect_to codes_path, notice: 'Code was successfully destroyed.'
  end

  private
    def set_code
      @code = Code.find(params[:id])
    end

    def code_params
      params.require(:code).permit(:name, :code)
    end
end

app/controllers/concerns/webhookable.rb
module Webhookable
  extend ActiveSupport::Concern

  def set_header
    response.headers["Content-Type"] = "text/xml"
  end

  def render_twiml(response)
    render text: response.text
  end
end

app/controllers/voice_controller.rb
class VoiceController < ApplicationController
  include Webhookable
  after_filter :set_header
  skip_before_action :verify_authenticity_token

  def start
    response = Twilio::TwiML::Response.new do |response|
      response.Gather(numDigits: '4', timeout: '10', action: check_voice_path, method: 'get') do |gather|
        gather.Say "To buzz in, please enter your four digit code, or stay on the line", voice: 'woman'
      end
      response.Redirect(real_human_voice_path, method: 'get')
    end

    render_twiml response
  end

  def check
    response = Twilio::TwiML::Response.new do |response|
      if code = Code.find_by_code(params['Digits'])
        response.Say("Thank you #{code.name}!", voice: 'woman')
        response.Play(digits: ENV['BUZZ_KEYS'])
      else
        response.Say("The code you entered, #{params['Digits']}, is not valid.", voice: 'woman')
        response.Redirect(start_voice_path, method: 'get')
      end
    end
    render_twiml response
  end

  def real_human
    response = Twilio::TwiML::Response.new do |response|
      response.Dial(ENV['FALL_THROUGH_PHONE_NUMBER'])
    end

    render_twiml response
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/codes/_form.html.erb
<%= form_for(@code) do |f| %>
  <%= f.label :code %><%= f.text_field :code %>
  <%= f.label :name %><%= f.text_field :name %>
  <% if @code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
      <% @code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/codes/edit.html.erb
<h1>Editing Code</h1>

<%= render 'form' %>

<%= link_to 'Back', codes_path %>

app/views/codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Codes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @codes.each do |code| %>
      <tr>
        <td><%= code.name %></td>
        <td><%= code.code %></td>
        <td><%= link_to 'Edit', edit_code_path(code) %></td>
        <td><%= link_to 'Destroy', code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Code', new_code_path %>

app/views/codes/new.html.erb
<h1>New Code</h1>

<%= render 'form' %>

<%= link_to 'Back', codes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CallBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>